// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/backup" | "/admin/banner" | "/admin/configuracoes" | "/admin/conteudo" | "/admin/dashboard" | "/admin/depoimentos" | "/admin/edicoes" | "/admin/faq" | "/admin/galeria" | "/admin/inscritos" | "/admin/kit" | "/admin/links" | "/admin/log" | "/admin/login" | "/admin/numeros" | "/admin/patrocinadores" | "/admin/playlist" | "/admin/premiacao" | "/admin/strava" | "/admin/usuarios"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/password" | "/api/content" | "/api/gphotos" | "/api/media" | "/api/media/[key]" | "/api/strava-resolve" | "/api/subscribe" | "/api/users" | "/api/users/[id]" | "/api/yt-playlist"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/backup": {}
  "/admin/banner": {}
  "/admin/configuracoes": {}
  "/admin/conteudo": {}
  "/admin/dashboard": {}
  "/admin/depoimentos": {}
  "/admin/edicoes": {}
  "/admin/faq": {}
  "/admin/galeria": {}
  "/admin/inscritos": {}
  "/admin/kit": {}
  "/admin/links": {}
  "/admin/log": {}
  "/admin/login": {}
  "/admin/numeros": {}
  "/admin/patrocinadores": {}
  "/admin/playlist": {}
  "/admin/premiacao": {}
  "/admin/strava": {}
  "/admin/usuarios": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/password": {}
  "/api/content": {}
  "/api/gphotos": {}
  "/api/media": {}
  "/api/media/[key]": { "key": string; }
  "/api/strava-resolve": {}
  "/api/subscribe": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/yt-playlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
